# Generated by Django 4.0.3 on 2022-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("img", models.ImageField(upload_to="images")),
                ("year", models.IntegerField(default=2022)),
                ("is_approved", models.BooleanField(default=False)),
                ("labels", models.ManyToManyField(to="core.label")),
            ],
        ),
    ]
