# Generated by Django 4.0.3 on 2022-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_movie_reference_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
