# Generated by Django 4.0.4 on 2022-04-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_movie_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="author",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
