# Generated by Django 4.0.4 on 2022-04-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_movie_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
