# Generated by Django 4.0.4 on 2022-06-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movie_is_processed_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='reference_url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
