# Generated by Django 4.0.4 on 2022-06-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_movie_img_remove_movie_reference_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='source',
            field=models.CharField(choices=[('csfd', 'ČSFD')], default='csfd', max_length=10),
        ),
    ]
