# Generated by Django 4.0.5 on 2022-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_movie_name_alter_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.CharField(choices=[('imdb', 'IMDB'), ('csfd', 'ČSFD')], default='csfd', max_length=10),
        ),
    ]
